### ISSUE TITLE
Les mails de demande de feedback contiennent du HTML

### ISSUE THREAD

**Issue by VincentLandais** [Zenika/feedzback#239]
La partie 'Commentaire' du mail de demande de feeback affiche des balise HTML.

Exemple:
```
Hello,<br><br>En ce mois de janvier...
```

Comportement attendu:
```
Hello,

En ce mois de janvier...
```

**Comment by patou** [comment]
Tu m'as devancé, j'allais ouvrir la même issue.

**Comment by lisequesnel** [comment]
Est-ce que le bug est toujours là ?
