### ISSUE TITLE
Ajout d'un dashboard métier pour suivre l'utilisation de FeedZback

### ISSUE THREAD

**Issue by lisequesnel** [Zenika/feedzback#296]
# Besoin

Nous n'avons aujourd'hui aucun moyen de suivre l'utilisation de FeedZback.

# Solution

Permettre la visualisation de questions métiers via un BigQuery et un LookerStudio.

- Nombre de demandes de feedbacks (répondues ou non)
- Nombre de feedbacks envoyés (spontanés ou non)
- Distribution par quantile du nombre de feedbacks reçus par personne

**Comment by avine** [comment]
Actuellement, après avoir répondu à une demande de feedZback, on ne peut pas savoir de manière absolue si le feedZback était spontané ou en réponse à une demande (sauf si lors de la demande, l'auteur de la demande a écrit un message).

**Comment by avine** [comment]
La métrique de base qu'on peut avoir dès à présent est : 
- Nombre de feedZbacks donnés par mois.

**Comment by lisequesnel** [comment]
> Actuellement, après avoir répondu à une demande de feedZback, on ne peut pas savoir de manière absolue si le feedZback était spontané ou en réponse à une demande (sauf si lors de la demande, l'auteur de la demande a écrit un message).

On ne cherche pas à distinguer les 2, il y a bien spécifié "spontanés ou non" donc on prend tout.

**Comment by lisequesnel** [comment]
> La métrique de base qu'on peut avoir dès à présent est :
> 
> * Nombre de feedZbacks donnés par mois (== Nombre de feedbacks envoyés (spontanés ou non))

on ne peut pas avoir dès à présent aussi le nombre de demandes (répondues ou non) ?

**Comment by avine** [comment]
> > Actuellement, après avoir répondu à une demande de feedZback, on ne peut pas savoir de manière absolue si le feedZback était spontané ou en réponse à une demande (sauf si lors de la demande, l'auteur de la demande a écrit un message).
> 
> On ne cherche pas à distinguer les 2, il y a bien spécifié "spontanés ou non" donc on prend tout.

Je n'ai pas compris.

**Comment by avine** [comment]
> > La métrique de base qu'on peut avoir dès à présent est :
> > 
> > * Nombre de feedZbacks donnés par mois (== Nombre de feedbacks envoyés (spontanés ou non))
> 
> on ne peut pas avoir dès à présent aussi le nombre de demandes (répondues ou non) ?

La seule différence entre un feedZback spontané et un feedZback en réponse à une demande c'est que le second peut avoir le champ "message" non vide.

En gros, à la fin du process, un feedZback initié par une demande, n'est pas différentiable d'un feedZback spontané.

Les métriques simples qu'on peut avoir dès aujourd'hui sont : 
- Nombre de feedZbacks terminés (spontané ou en réponse à une demande)
- Nombre de feedZbacks demandés et pas encore répondus

**Comment by noancloarec** [comment]
Voici les visualisation que je compte créer (je reprends les éléments de Lise) : 
- Un historique du nombre de feedzback envoyés dans toutes l'app (par jour, par semaine, par mois)
- Un historique du nombre de demandes feedzback envoyés dans toutes l'app (par jour, par semaine, par mois)

Pour la vue _Distribution par quantile du nombre de feedbacks reçus par personne_ il faut qu'on prenne le temps de définir à quoi ça peut ressembler.

**Comment by avine** [comment]
Voici les stats que je peux te fournir directement du backend de FeedZback :) 
https://server.staging.feedzback.znk.io/feedback-stats

**Comment by lisequesnel** [comment]
> Voici les visualisation que je compte créer (je reprends les éléments de Lise) :
> 
> * Un historique du nombre de feedzback envoyés dans toutes l'app (par jour, par semaine, par mois)
> * Un historique du nombre de demandes feedzback envoyés dans toutes l'app (par jour, par semaine, par mois)
> 
> Pour la vue _Distribution par quantile du nombre de feedbacks reçus par personne_ il faut qu'on prenne le temps de définir à quoi ça peut ressembler.

@noancloarec a ta dispo pour discuter ensemble des métriques pertinentes et de comment les représenter

**Comment by avine** [comment]
> Voici les visualisation que je compte créer (je reprends les éléments de Lise) :
> 
> * Un historique du nombre de feedzback envoyés dans toutes l'app (par jour, par semaine, par mois)
> * Un historique du nombre de demandes feedzback envoyés dans toutes l'app (par jour, par semaine, par mois)
> 
> Pour la vue _Distribution par quantile du nombre de feedbacks reçus par personne_ il faut qu'on prenne le temps de définir à quoi ça peut ressembler.

Concernant le point 2 : si je comprends bien, il s'agit des demandes de feedZback en attente de réponse.

A mon sens, ce nombre n'est pertinent qu'à l'instant présent.
Car une demande de feedZback disparaît une fois répondue.

De plus, une demande de feedZback non répondue peut être supprimée par le demandeur au délà de 60 jours.
Donc sur le long terme, le nombre de demande non répondues de l'année dernière par exemple tendra à être nul.

Tout cela est vrai si les statistiques du passé sont calculées par LookerStudio à l'instant présent.
Par contre, si comme dans ce qu'à mis en place Pierre Nicoli, les stats sont calculées sur la base des événements de FireStore alors dans ce cas, on peut avoir des métriques sur les demandes de feedZbacks.

**Comment by avine** [comment]
> de mon point de vue, pour les métriques métier ces statistiques via un endpoint prédéfini ne conviennent pas car on doit pouvoir ajuster la date, ajouter des métriques, etc, facilement (danc sans dev) directement ddepuis l'interface Looker Studio

Le endpoint fournit l'historique complet des feedZbacks "done".
Donc tu peux ajuster la date en ne prenant qu'une partie des données non ?
ça peut pas être utilisé dans LookerStudio comme une source de données parmi d'autres ?

**Comment by noancloarec** [comment]
Première proposition d'implémentation dans #416 


![Image](https://github.com/Zenika/feedzback/assets/15016365/78c924ad-1114-4a45-9037-45efcf129ed4)

**Comment by noancloarec** [comment]
Reste à faire 

- [ ] Intégrer et tester le déploiement des cloud functions au script circle-ci (en tagant cette branche dev-x-y-z)
- [ ] Restreindre les accès R&W au dataset _firestore_export_ à un service-account dédié. Garder les données personnelles dans ce dataset. Vérifier que LookerStudio n'a pas accès à ce dataset
- [ ] Documenter l'étape précédente pour pouvoir la répéter sur staging et prod
- [ ] Merger sur main et tester la procédure avec un⸱e autre utilisateur⸱ice sur staging pour s'assurer que la doc est correcte.

**Comment by noancloarec** [comment]
Bonjour @lisequesnel , je te propose de fermer cette issue que nous avons éclatée en 3 autres (#474 #475 et #488)

**Comment by noancloarec** [comment]
Lise a dit oui
