### ISSUE TITLE
Quand je sauvegarde en brouillon ma "réponse à une demande feedZback", celui-ci n'apparaît pas dans la liste des brouillons du parcours "Donner un feedZback spontané"

### ISSUE THREAD

**Issue by avine** [Zenika/feedzback#301]
Ce n'est pas un bug technique.
C'est l'expérience utilisateur qui est déroutante.

### Comment reproduire

- Etant donné que j'ai reçu une demande de feedZback par mail.
- Je clique sur le bouton "Donner mon feedback"
- J'arrive sur la page en mode connecté (même si elle fonctionne en mode déconnecté) : `/give/requested/[CODE_SECRET]`
- Je commence à remplir mon feedback et je clique sur sauvegarder
- Comme je suis connecté, je me balade dans l'app puis je clique sur "Donner"
- Là, je ne retrouve pas mon brouillon dans la liste de mes brouillons !

Techniquement c'est normal, car cette liste de brouillons contient les brouillons des feedbacks spontanés.
Mais l'utilisateur s'attendais à retrouver son brouillon à cet endroit.

Le brouillon existe bien.
Si l'utilisateur clique à nouveau dans le lien fourni dans l'email, il revient bien à la page `/give/requested/[CODE_SECRET]` et peut reprendre la rédaction de son feedback là où il en était.

Autre chemin possible : 
- Il va dans la page Mes feedZbacks -> onglet "à donner"
- Il clique sur l'oeil "Voir le feedZback" 
- Il retrouve alors la demande du feedZback et un bouton "Donner" qui le ramène bien à la page `/give/requested/[CODE_SECRET]`

-----

Il faut bien comprendre que techniquement, les parcours "donner un feedback spontané" et "répondre à une demande de feedback" sont très différents.
La différence centrale étant qu'un utilisateur NON connecté peut répondre à une demande de feedback (use-case : il est externe à Zenika).

C'est dans la UI que les 2 parcours semblent les mêmes car quand je réponds à une demande de feedback, même si l'URL est `/give/requested/[CODE_SECRET]` (et non `/give`) le titre de la page est le même "Donner du feedZback" !
Même dans le menu, le bouton "Donner" est bien souligné en rouge.

Mais encore une fois, quand j'ai développé cette partie, il m'a semblé logique de fusionner les 2 parcours d'un point de vue UI bien qu'ils étaient très différents d'un point de vue technique.

En fait visuellement, la seule nuance c'est que dans la page de réponse il y a ce fameux texte : "Vous répondez à la demande de Feedback de intel...".

**Comment by avine** [comment]
Voilà la solution que je propose pour aiguiller l'utilisateur dans ce parcours : 

<img width="1218" alt="Capture d’écran 2024-01-14 à 00 03 21" src="https://github.com/Zenika/feedzback/assets/1133214/49a1d7dc-5515-4936-a67e-f1c97d3b312d">

**Comment by lisequesnel** [comment]
Je comprends le problème.
Pour moi, le plus intuitif pour l'utilisateur serait de pouvoir retrouver ses brouillons dans "Donner" que ce soit un brouillon d'un feedzback spontané ou à la suite d'une demande. La preuve : c'est là où on a cherché intuitivement tous les 2 lors de la démo, donc c'est là que les utilisateurs iront chercher aussi.
