### ISSUE TITLE
Clarifier le message d'erreur quand on utilise son propre email

### ISSUE THREAD

**Issue by lisequesnel** [Zenika/feedzback#312]
# Description du bug
Il n'est pas possible de demander un feedzback à soi-même cependant, le message d'erreur n'est pas claire...

<img width="991" alt="image" src="https://github.com/Zenika/feedzback/assets/23451175/374938f0-d09e-4ff9-8855-6836f7f814f0">

# Etapes pour reproduire

1. Aller sur la page "Demander"
2. remplir sa propre adresse email
3. Valider

# Comportement attendu

Message "Vous ne pouvez pas vous envoyer un mail à vous-même."

**Comment by avine** [comment]
Il faut ajouter une validation côté front : 
- Un validateur existe déjà : 
  - `client/src/app/shared/form/forbidden-values/forbidden-values.validator.ts`
- Le message d'erreur est générique et disponible ici : 
  - `src/app/shared/form/validation-error-message/validation-error-message.ts`

Pour le customiser, il faut améliorer le pipe suivant : 
- `src/app/shared/form/validation-error-message/validation-error-message.pipe.ts`

```html
<mat-error>{{ positive.errors | validationErrorMessage : customMessages }}</mat-error>
```

**Comment by avine** [comment]
C'est une bonne issue pour commencer à contribuer au projet.
Je reste à disposition pour échanger sur la solution avec le dev qui prendra le point.

**Comment by avine** [comment]
Faire de même pour le settings du manager.

**Comment by avine** [comment]
Le message d'erreur est désormais clair lorsque je saisis mon propre email : 
- Quand je fais une demande de feedZback
- Quand je donne un feedZback spontané
- Quand je saisis l'email de mon manager
