### ISSUE TITLE
Un seul brouillon est possible par personne

### ISSUE THREAD

**Issue by lisequesnel** [Zenika/feedzback#318]
# Description du bug

Lorsque j'ai déjà un brouillon à écrire pour 1 personne, si je souhaite en écrire un autre à la même personne et que j'enregistre ce brouillon, le 2ème brouillon écrase le 1er brouillon.

# Etapes pour reproduire

1. Aller sur "Donner", et commencer à donner un feedback spontané à une personne, enregistrer le brouillon
2. Revenir à l'accueil
3. Aller sur "Donner" et commencer à donner un autre feedback à la même personne, enregistrer le brouillon
4. Revenir à l'accueil
5. Revenir sur "Donner" et cliquer sur "brouillons"
6. Constater que le 1er brouillon a été écrasé

# Comportement attendu

Pouvoir avoir plusieurs brouillons pour une même personne

**Comment by avine** [comment]
Actuellement, pour un feedZback spontané, le brouillon est associé à l'email du receveur du feedback.
C'est pourquoi on ne peut pas avoir plusieurs brouillons.

Ce choix d'implémentation permet, lorsque je valide le feedZback d'effacer l'éventuel unique brouillon associé.

**Comment by avine** [comment]
A titre d'info, pour les brouillons de réponse à une demande de FeedZback : 
Le brouillon est associé à la demande, donc on peut tout à fait avoir plusieurs brouillons avec le même destinataire.

**Comment by lisequesnel** [comment]
j'ai changé le label (cependant d'un point de vue extérieur, cela peut-être considéré comme un bug).

> Quel est le besoin ?

La 1 : Je veux envoyer envoyer plusieurs feedZbacks à la même personne dans la même période temporelle et je veux profiter de la fonctionnalité des brouillons même dans ce cas d'usage.

**Comment by avine** [comment]
C'est assez couteux techniquement comme changement.
J'aimerai challenger ce besoin.
Perso, je pense que c'est un cas d'usage à la marge.

Pourquoi c'est couteux ?
- Actuellement, le formulaire de feedZback spontané n'est pas couplé à la notion de brouillon
- Simplement, quand j'envoie un feedZback spontané, le serveur efface l'unique brouillon éventuel pour ce destinataire.
- Côté front, appliquer un brouillon signifie simplement pré-remplir les champ du formulaire avec les données du brouillon
- En d'autres termes, le formulaire n'a pas besoin de tracker qu'il est lié a un brouillon
