### ISSUE TITLE
Ajouter un wording pour mieux expliquer le partage du feedback au manager

### ISSUE THREAD

**Issue by lisequesnel** [Zenika/feedzback#320]
# Besoin

L'intérêt de partager le feedback au manager est pas explicite.

# Solution

Ajouter des petits wordings à côté du feature toggle :

sur le feedZback spontané : "Partager votre feedback avec le manager du destinataire est recommandé. Le rôle d'un manager est d'aider ses managés à bien recevoir et tirer parti des feedbacks reçus."
sur la demande : "Partager le feedback avec votre manager est recommandé. Le rôle d'un manager est d'aider ses managés à bien recevoir et tirer parti des feedbacks reçus."

Ajouter aussi ça dans le message "vert" sur la réponse à une demande : "Vous répondez à une demande [blabla].... Il ou elle a demandé à ce que le feedback soit partagé avec son manager. Le rôle d'un manager est d'aider ses managés à bien recevoir et tirer parti des feedbacks reçus."

**Comment by avine** [comment]
Il faudrait améliorer le wording : "Le rôle d'un manager est d'aider ses managés à bien recevoir et tirer parti des feedbacks reçus.".

Car il laisse entendre qu'un consultant ne sait pas bien accueillir un feedback sans l'aide de son manager.

**Comment by lisequesnel** [comment]
> Il faudrait améliorer le wording : "Le rôle d'un manager est d'aider ses managés **à bien recevoir** et tirer parti des feedbacks reçus.".
> 
> Car il laisse entendre qu'un consultant ne sait pas bien accueillir un feedback sans l'aide de son manager.
> 
> Le but du partage de feedback avec le manager est plutôt un moyen pour le manager de suivre la performance de ses consultants en toute transparence avec le managé (puisque c'est lui qui fait cette demande au départ).

Que proposes-tu comme wording ?
