### ISSUE TITLE
Impossible d'utiliser les "groupes de mail" gmail / mauvais code http

### ISSUE THREAD

**Issue by Ithrandil** [Zenika/feedzback#321]
# Description du bug

Chez mon client j'ai utilisé le groupe de mail de mon équipe qui rassemble tout les membres de l'équipe. Ils ont bien tous reçu le mail.
Il y a eu un premier membre qui a répondu. Les suivants ont eu une page d'erreur en suivant le lien (normal je pense).

Par contre, une des personnes avait l'onglet ouvert avant la validation du premier commentaire. Quand il a validé som message, il a bien eu un message d'erreur, mais par contre il a eu une réponse 201 au POST et je ne vois pas le feedback de mon côté.

# Etapes pour reproduire

1. Envoyer une demande de feedback à un groupement de mail
2. Ouvrir la demande avec deux comptes différents
3. Valider un premier feedback
4. Valider un deuxième feedback avec le deuxième compte
5. Affichage du message d'erreur mais un POST en success

# Comportement attendu

- Pouvoir envoyer une demande à un groupement de mails 
ou
- Ne pas renvoyer une 201

( N'hésitez pas si ce n'est pas clair, je suis un Z à Niort :D )

**Comment by avine** [comment]
Ce n'est pas un bug.
Actuellement, pour faire une demande de feedZback, seules les adresses emails de personnes physiques sont supportées.

Il y a un tooltip qui s'affiche lorsque passe la souris sur le champs "Emails de vos collègues" :

<img width="718" alt="Capture d’écran 2024-01-29 à 18 32 02" src="https://github.com/Zenika/feedzback/assets/1133214/a9995388-e572-46e5-831f-2ad85c477ec7">
s.

Côté implémentation, une demande de feedZback crée un token unique permettant de répondre à cette demande.
La demande ne peut être répondue que par une seule personne et une seule fois (token à usage unique).

Pour répondre à ce besoin, il faudrait : 
- Connaître la liste des personnes physiques qui se "cache" derrière le mail de la liste de diffusion
- Ajouter en base une demande de feedZback pour chacunes de ces personnes physiques
Mais je ne pense pas que ce soit possible, car le mail de la liste de diffusion est opaque.

**Comment by avine** [comment]
Par contre je vais regarder pour le code HTTP.

**Comment by avine** [comment]
Par contre je vais regarder pour le code HTTP.

**Comment by Ithrandil** [comment]
Bien vu pour la tooltip. Je ne suis pas un bon user. 😀 Je me doutais que ça devait être un token à usage unique mais j'ai tout de même décrit pour expliquer le cas d'usage. C'était surtout pour le code http. Merci bien pour le retour en tout cas!

**Comment by avine** [comment]
Tu es le user idéal puisque tu nous aide à identifier les cas à la limite... 😉

**Comment by avine** [comment]
C'est corrigé pour les codes de retour HTTP.
