### ISSUE TITLE
Allow users to give their feedback about FeedZback

### ISSUE THREAD

**Issue by avine** [Zenika/feedzback#332]
- En tant qu'utilisateur connecté, je peux noter l'app de 1 à 5.
- En tant qu'utilisateur en train de répondre à une demande de feedZback, je peux également noter l'app de 1 à 5.
- Si j'ai mis une note, je peux la mettre à jour ultérieurement
- Noter l'app consiste à mettre une note, pas besoin de commentaire (en cas de mécontentement, l'utilisateur peut toujours ouvrir une issue sur GitHub)
- Dans l'app, on peut afficher la note comme sur le site Amazon

Example of this feature on Amazon :

<img width="377" alt="Capture d’écran 2024-02-01 à 16 42 13" src="https://github.com/Zenika/feedzback/assets/1133214/31d259b3-d774-4ee9-a02e-af8a24b73b78">

<img width="309" alt="Capture d’écran 2024-02-01 à 16 48 44" src="https://github.com/Zenika/feedzback/assets/1133214/1130e173-a0a9-4b38-9e11-1c6e01915021">

**Comment by avine** [comment]
Techniquement, on crée une nouvelle collection Firestore.

Le modèle étant quelque chose comme :

```ts
type AppReviewCollection = {
  [userEmail]: AppReview;
};

type AppReview = {
  note: 1 | 2 | 3 | 4 | 5;
  // Eventuellement d'autres champs demain...
};
```

Donc en base, la note est associée à une personne, mais pour les requêtes GET on fait `Object.value(Collection)` pour anonymiser les réponses.

**Comment by lisequesnel** [comment]
Attention à ça, personnellement je suis pas pour, on prône avec feedZback d'avoir du feedback constructif, élaboré, et ce mode de notation ne correspond pas du tout à ça et est très biaisé.
