### ISSUE TITLE
Amélioration de wording

### ISSUE THREAD

**Issue by lisequesnel** [Zenika/feedzback#373]
# Wording 1

## Problème
Dans le menu "Répondre", quand il n'y a pas de demandes en cours à répondre :
<img width="1001" alt="image" src="https://github.com/Zenika/feedzback/assets/23451175/6f0f2c5c-afae-4d6d-bad9-9b8b38ae9230">

## Solution

Enlever le "à traiter", qui fait très "tâches"

# Wording 2

## Problème
Dans le menu "Demander", après avoir cliqué sur "Envoyer" :
<img width="425" alt="image" src="https://github.com/Zenika/feedzback/assets/23451175/dc810793-c3fd-41b6-95d4-76e3ef503dd7">

## Solution

"Confirmation demandée" -> "Envoyer la demande de FeedZback ?"
"La requête sera traitée si vous décidez de confirmer." -> "Une demande de FeedZback va être envoyée à xxx."
"Confirmer" -> "Envoyer"

# Wording 3

## Problème
Dans les menus "Donner" et "Répondre" après avoir écrit quelque chose sans le sauvegarder et en quittant la page :
<img width="578" alt="image" src="https://github.com/Zenika/feedzback/assets/23451175/66848a5b-14d4-4467-8651-e3ff3b6a59ce">

## Solution

"Modifications non sauvegardées" -> "Quitter la page ?"
"Les modifications apportées seront perdues si vous décidez de continuer." -> "Le FeedZback que vous avez commencé à écrire à xxx [si renseigné] n'a pas été sauvegardé. **Les modifications apportées seront perdues** si vous décidez de quitter la page."
"Continuer" -> "Quitter la page"

# Wording 4

## Problème

Dans les menus "Donner" et "Répondre" après avoir écrit quelque chose et cliqué sur le bouton "Envoyer" :
<img width="489" alt="image" src="https://github.com/Zenika/feedzback/assets/23451175/ce44efc2-62f1-4f37-bb9d-1d05611e5ed5">

## Solution

"Confirmation demandée" -> "Envoyer le FeedZback ?"
"Une fois confirmé, votre feedZback ne peut plus être modifié." -> "Votre FeedZback va être envoyé à xxx, vous ne pourrez plus le modifier."
"Confirmer" -> "Envoyer"

# Wording 5

## Problème

A la reprise d'un brouillon dans les menus "Donner" et "Répondre" alors qu'on a déjà quelque chose d'écrit :
<img width="578" alt="image" src="https://github.com/Zenika/feedzback/assets/23451175/c714c1fc-c899-473b-bb5c-73ea688de0af">

## Solution

"Modifications non sauvegardées" -> "Reprendre le brouillon ?"
"Les modifications apportées seront perdues si vous décidez de continuer." -> "Le FeedZback que vous avez commencé à écrire à xxx [si renseigné] n'a pas été sauvegardé. **Les modifications apportées seront perdues** si vous décidez de reprendre le brouillon pour yyy". 
"Continuer" -> "Reprendre le brouillon"

**Comment by avine** [comment]
Actuellement, les messages dans les popup sont génériques.
Ils ne sont pas ou peu liés à la feature fonctionnelle dans laquelle ils apparaissent.

Le point qui peut être traité : 

- Wording 1

En l'état, les points suivants ne peuvent pas être traités : 

- Wording 2

- Wording 4 : 
   Actuellement, seul le message suivant est paramétrable :  "Une fois confirmé, votre feedZback ne peut plus être modifié."

-  Wording 3 et 5 : 
   C'est la même popup qui est utilisée dans ces 2 scénarios (je navigue vers une autre page, je veux appliquer un brouillon qui va écraser quelque chose).

Pour ces points, est-ce qu'on peut trouver un wording générique qui répond au besoin ?

**Comment by avine** [comment]
Je propose les textes suivants.
Le but étant de garder les textes génériques car actuellement l'implémentation des popups n'est pas liée au contexte métier.

Cas n°1) 
Je clique sur "Envoyer" : 
- une demande de feedZback
- ma réponse à une demande de feedZback
- mon feedZback spontané
 
Example pour une demande de feedZback : 
<img width="1002" alt="Capture d’écran 2024-02-26 à 16 14 20" src="https://github.com/Zenika/feedzback/assets/1133214/10007bd4-fb38-4019-a3a9-72e89a747b56">

Cas n°2)
J'ai commencé à remplir le formulaire pour  réponse à une demande de feedZback ou feedZback spontané ET : 
- Je tente d'appliquer un brouillon enregistré
- Je tente de naviguer vers une autre page

Exemple pour feedZback spontané : 
<img width="1008" alt="Capture d’écran 2024-02-26 à 16 18 30" src="https://github.com/Zenika/feedzback/assets/1133214/5c4e59c2-7cad-4ca4-b40d-dc8b65cf502c">

Dites-moi si ça vous convient ?

**Comment by avine** [comment]
Pour info, il y a 2 cas où on on demande confirmation avant de transmettre la demande au serveur :

1) Envoi des données
2) Suppression des données

Exemples : 
<img width="577" alt="Capture d’écran 2024-02-27 à 12 30 44" src="https://github.com/Zenika/feedzback/assets/1133214/9dc381cd-7a22-4d07-b94c-38f1eccfb243">
<img width="874" alt="Capture d’écran 2024-02-27 à 12 38 04" src="https://github.com/Zenika/feedzback/assets/1133214/5f18df52-4d11-4aa1-bf21-48b899fd68ec">

**Comment by lisequesnel** [comment]
> Le but étant de garder les textes génériques car actuellement l'implémentation des popups n'est pas liée au contexte métier.

Justement, c'est ce que j'ai à reprocher, le fait que ce soit trop générique provoque la mécompréhension et l'impersonnalisation...

A mon sens on devrait avoir du contexte métier dans les pop-up pour mieux comprendre ce que l'on est en train de faire sans pour autant faire flipper les utilisateurs.

**Comment by avine** [comment]
Je propose de faire un test utilisateur.
