### ISSUE TITLE
Modification des wordings pour la fonctionnalité management

### ISSUE THREAD

**Issue by lisequesnel** [Zenika/feedzback#378]
# Need from the user's point of view

- Sur la page de réponse à un feedback demandé :
"Ce feedback sera partagé avec le manager de la personne concernée, pour leur permettre d'échanger sur son contenu." si l'option est activée

- Sur la page de demande d'un feedback :
"Partager le feedback avec votre manager est recommandé. Vous pourrez échanger avec votre manager et ainsi recueillir et bénéficier au mieux des feedbacks reçus."

- Sur la page d'envoi de feedback spontané (donc par un Z) :
"Partager votre feedback avec le manager du destinataire est recommandé. Cela leur permettra d'échanger dessus et de bénéficier au mieux du contenu des feedbacks reçus."

**Comment by avine** [comment]
Pour la 3e partie : "Partager votre feedback avec le manager de votre collègue est recommandé. Cela leur permettra d'échanger dessus et de bénéficier au mieux du contenu des feedbacks reçus."
