### ISSUE TITLE
App review : say "thank you" and prevent multiple post review

### ISSUE THREAD

**Issue by avine** [Zenika/feedzback#382]
# The problem 

For example, when the user give a spontaneous feedback and reach the "Success" page : 
He is able to post a review about the app.
But at this point, he can post the review multiple times.

# Expected behavior

The user should be able to post its review only once at this point.

**Comment by lisequesnel** [comment]
Je propose de séparer la partie "dire merci", une autre issue est à ce sujet, et la fonctionnalité n'est pas encore prête, il y a plein de questions.

**Comment by avine** [comment]
Done
