### ISSUE TITLE
Annuler une demande de feedback / Cancel a feedback request

### ISSUE THREAD

**Issue by lisequesnel** [Zenika/feedzback#387]
# Need from the user's point of view

Quand cela fait trop longtemps qu'une demande a été envoyée ou bien que la personne est partie de l'entreprise, un utilisateur veut pouvoir annuler une demande de feedback.

When it has been too long since a request was sent or the person has left the company, a user wants to be able to cancel a feedback request.

**Comment by avine** [comment]
Voici les différentes étapes : 

Demande récente : ne peut pas être supprimée 
<img width="574" alt="Capture d’écran 2024-02-27 à 11 59 30" src="https://github.com/Zenika/feedzback/assets/1133214/a02d0ff7-1d3c-4a67-843d-93a33d730678">

Demande ancienne : plus de 30 jours depuis la dernière relance
<img width="573" alt="Capture d’écran 2024-02-27 à 11 59 00" src="https://github.com/Zenika/feedzback/assets/1133214/bdc9cd1e-c652-468d-b9dd-cc544915cdd3">

Lorsqu'on clique sur "Supprimer" : 
<img width="575" alt="Capture d’écran 2024-02-27 à 12 01 11" src="https://github.com/Zenika/feedzback/assets/1133214/638b7d25-fe73-4f98-a147-3432b9f3995e">

Une la suppression terminée : 
<img width="577" alt="Capture d’écran 2024-02-27 à 12 01 18" src="https://github.com/Zenika/feedzback/assets/1133214/506c6865-3d53-4391-86e7-50fb55eecffb">

**Comment by lisequesnel** [comment]
Le mot "supprimer" ne convient pas, on est plus sur une "annulation" : on ne doit pas supprimer la donnée en base, ça a de la valeur de savoir qu'une demande a été faite mais pas répondue et donc annulée derrière
