### ISSUE TITLE
Archiver un feedback / Archive feedback

### ISSUE THREAD

**Issue by lisequesnel** [Zenika/feedzback#389]
# Need from the user's point of view

Lorsqu'un feedback est trop vieux, n'est plus pertinent, un utilisateur veut pouvoir ne plus l'afficher dans sa liste de feedback reçus. Ajouter un bouton pour archiver le feedback dans le détail du feedback, et un filtre pour filtrer les feedbacks archivés.

When feedback is too old and no longer relevant, a user wants to be able to no longer display it in their list of feedback received. Add a button to archive the feedback in the feedback detail, and a filter to filter the archived feedback.

**Comment by avine** [comment]
Je propose de découper la feature en 2 PR :
1. Bouton archiver dans la vue détaillée d'un feedZback terminé
2. Possibilité de consulter les feedZback archivés 

Concernant ce second point, je propose :

- de challenger le besoin de visualiser les feedZbacks archivés. Peut-être qu'une fois archivé il n'est tout simplement plus accessible (il reste en base bien sûr pour les besoins statistiques)

- de les afficher dans une page dédiée (plutôt que dans la vue principale avec un filtre - comme dans Gmail par exemple). Techniquement ça sera plus facile et le besoin sera couvert.

**Comment by avine** [comment]
J'ai gardé cette issue pour la partie 1) Archivage des feedZbacks ayant un statut "done".
Pour le moment, il n'y a pas de moyen de visualiser les feedZbacks archivés

**Comment by avine** [comment]
Screenshot de la fonctionnalité : 
<img width="1012" alt="Capture d’écran 2024-03-03 à 21 42 43" src="https://github.com/Zenika/feedzback/assets/1133214/22491e4a-d769-464b-9472-30a2b6f2c42b">
