### ISSUE TITLE
💡Pop up - revue des libellés / Pop-uo labels review

### ISSUE THREAD

**Issue by jeanphibaconnais** [Zenika/feedzback#405]
# Pop up | Revue des libellés / Label review

En pleine préparation de mon EA, j'utilisais feedZback et je suis tombé sur des popup qui m'ont paru très "froide" et assez éloigné de l'utilisateur. Par exemple sur les brouillons le titre "Confirmer l'action?". Ne pourrait-on avoir quelque chose de plus précis et proche de l'utilisateur et de son actions en cours, comme "Voulez quitter votre feedZback sans enregistrer ?" et le libellé associé serait "les modifications apportées seront perdues".

Pour la popup de confirmation d'envoie de demande de feedZback, le "Cliquez sur confirmer pour finaliser l'envoie de votre demande" est un peu "dur. Si on tourne cela sous la forme de quelque chose du style "Confirmez-vous l'envoie votre demande ?", le texte en dessous n'a plus de raison d'être et seuls les boutons "oui" / "non" permettraient de répondre à la question. 

 --- 

I am using feedZBack for ma Annual Interview and I think the popup is a little bit technical. Could we have labels more specific for example  "Voulez quitter votre feedZback sans enregistrer ?" ?

**Comment by avine** [comment]
Il y a 2 fonctionnalités distinctes : 
- Prévenir avant de perdre le contenu d'un formulaire qu'on a commencé à remplir (LeaveForm)
- Demander confirmation avant de finaliser une action (ConfirmBeforeSubmit)

## LeaveForm

Prenons le cas de la page "Donner du feedZback spontané".
Il y a 2 use-case où la popup va apparaître : 
- Si je tente de naviguer vers la page d'accueil par exemple
- Si je tente d'appliquer un brouillon qui va écraser le contenu du formulaire actuel
Ma contrainte technique c'est que c'est le même code qui est exécuté dans les 2 cas.
Bien sûr tout est possible en informatique mais je cherche à limiter la complexité du code.
C'est pourquoi il serait judicieux de trouver un texte qui s'applique à ces 2 cas.

### Ma proposition est la suivante : 

<img width="973" alt="Capture d’écran 2024-02-29 à 22 04 30" src="https://github.com/Zenika/feedzback/assets/1133214/c1ed1d59-6e97-4070-bac6-50beadee852d">

Mettons-nous à la place de l'utilisateur : 
Given
J'ai commencé à remplir le formulaire et d'un coup, je me dis : "ça serait bien que j'aille voir la liste de mes feedZbacks reçus..."
Ou bien : "ça serait bien que je continue le brouillon que j'ai commencé la semaine dernière..."
When 
Je clique sur le lien "Mes feedZbacks" ou "J'applique un brouillon enregistré"
Then
Une popup me préviens : 
"Tu dois confirmer cette action (action de naviguer / action d'appliquer un brouillon) !"
"Attention, tu va perdre le travail que tu as commencé"

**Comment by avine** [comment]
## LeaveForm

Prenons le cas de la page "Donner du feedZback spontané".

Il y a 2 use-case où la popup va apparaître : 
- Si je tente de naviguer vers la page d'accueil par exemple
- Si je tente d'appliquer un brouillon qui va écraser le contenu du formulaire actuel

Ma contrainte technique c'est que c'est le même code qui s'exécute dans les 2 cas.
Bien sûr tout est possible en informatique mais je cherche à limiter la complexité du code.
C'est pourquoi il serait judicieux de trouver un texte pertinent qui est valable pour les 2 cas.

#### Ma proposition est la suivante : 

<img width="973" alt="Capture d’écran 2024-02-29 à 22 04 30" src="https://github.com/Zenika/feedzback/assets/1133214/c1ed1d59-6e97-4070-bac6-50beadee852d">


Mettons-nous à la place de l'utilisateur : 

#### Given
J'ai commencé à remplir le formulaire et d'un coup, je me dis : "ça serait bien que j'aille voir la liste de mes feedZbacks reçus..."
Ou bien : "ça serait bien que je continue le brouillon que j'ai commencé la semaine dernière..."

#### When 
Je clique sur le lien "Mes feedZbacks" ou "J'applique un brouillon enregistré"

#### Then
Une popup me préviens : 
"Tu dois confirmer cette action (action de naviguer / action d'appliquer un brouillon) !"
"Attention, tu va perdre le travail que tu as commencé"

Je peux alors décider de cliquer sur "Confirmer" en connaissance de cause que je vais poursuivre mon action et perdre le contenu du formulaire entamé.

**Comment by avine** [comment]
> Concernant la proposition de Jean-Phi  : 
> "Voulez-vous quitter votre feedZback sans enregistrer ?"

Ce qui est déroutant, c'est que ce que je veux, ma volonté, c'est de naviguer vers une autre page ou appliquer un brouillon.
Pourquoi on me demande si "je veux" quitter mon feedZback ?

Ma réponse serait dans ce cas : "Ben non, gros béta, je veux pas quitter mon feedZback sans enregistrer ; je veux juste naviguer vers une autre page ; ce site ne comprends pas ce que je suis en train de faire..."

**Comment by avine** [comment]
Tiens, dans une appli télé, j'ai trouvé un texte assez proche du tiens :) 

>Quitter la lecture en cours
>
>Vous allez quitter votre lecture en différé sur cette chaîne, voulez-vous continuer ?
>
> Oui   Non

Adapté à notre use-case, ça donnerai quelque chose comme ça pour le cas `LeaveForm` :
<img width="791" alt="Capture d’écran 2024-03-01 à 00 36 33" src="https://github.com/Zenika/feedzback/assets/1133214/489f278a-d1d2-4077-965f-aadf51b634d6">

Si cette approche convient à Lise, je vais voir comment adapter ce pattern à l'ensemble des popup.
Dans ce cas, on essaie d'avoir à chaque fois les boutons oui / non.

**Comment by jeanphibaconnais** [comment]
Merci pour tes réponses. Effectivement, avoir des boutons "oui/non" c'était l'idée rapidement que je mettais dans l'issue, je ne sais pas si la solution à mettre en place, c'était plus un ordre d'idée que je mentionnais. C'est vrai que sur la plupart des sites, le bouton est vraiment un verbe représentant l'action à faire. Meme si la question est du type "oui/non", la réponse est un verbe "confirmer/annuler".

ha et sur les modales il faudrait harmoniser le fait d'avoir un icone ou non 😄

**Comment by avine** [comment]
Concernant les icône, tu as raison, je vais toutes les enlever car ça ne s'affiche pas bien sur mobile et quand on essaie de mettre un peu de css flexbox dans le titre des modèles de Material ça par en vrille..

**Comment by avine** [comment]
Mon besoin c'est vraiment d'identifier un pattern qui fonctionne et que je peux ensuite décliner sur l'ensemble des popup. 

Le principe est connu et consiste à jouer sur le fait qu'au bout de 2 ou 3 popup, le visiteur va inconsciemment identifier le pattern et va donc immédiatement comprendre ce qui es5 demandé.

**Comment by avine** [comment]
Je pense avoir compris l'enjeu : 

### Exemple avec la popup LeaveForm 

#### (1) Est-ce que la popup se met à la place de l'utilisateur ?
ça donne "Confirmer l'action ?"

#### (2) Est-ce que la popup se met à la place de l'interlocuteur ?
ça donne "Quitter le formulaire ?"


Ma conclusion est la suivante : 
Pour une popup de type LeaveForm, le besoin c'est de mettre en garde l'utilisateur sur ce qu'il va perdre, donc le message est : "Quitter le formulaire ?" (la popup est à la place de l'interlocuteur (2) qui préviens du danger)

Pour une popup de type ConfirmBeforeSubmit, le besoin c'est juste d'être sûr qu'il n'a pas cliqué par mégarde sur "envoyer", donc le message est : "Confirmer l'envoi ?" (la popup se met à la place de l'utilisateur (1)  pour l'accompagner jusqu'à la dernière étape de ce qu'il va faire)

Je vais faire une proposition dans ce sens :)

**Comment by avine** [comment]
En fait j'ai compris la source du problème, c'est le bouton "Envoyer" initial, qui en fait n'envoie rien puisqu'il faut cliquer dans la popup pour que l'envoi soi effectif !!!

Et si à la place on mettait "Continuer", ça serait bien ?
<img width="560" alt="Capture d’écran 2024-03-01 à 13 05 05" src="https://github.com/Zenika/feedzback/assets/1133214/bf8108e5-2c47-4059-8cb8-44c4be1dc58a">

**Comment by avine** [comment]
Voici ma proposition : 

## ConfirmBeforeSubmit

<img width="1037" alt="Capture d’écran 2024-03-01 à 14 15 06" src="https://github.com/Zenika/feedzback/assets/1133214/b00f2250-3373-4a98-a24b-a5261b119928">
<img width="1024" alt="Capture d’écran 2024-03-01 à 14 15 42" src="https://github.com/Zenika/feedzback/assets/1133214/7a0a1add-359a-42eb-9130-e1f081357931">
<img width="1019" alt="Capture d’écran 2024-03-01 à 14 16 10" src="https://github.com/Zenika/feedzback/assets/1133214/7efb4c7c-feab-4513-836e-ed52596c9a95">

## LeaveForm

<img width="1020" alt="Capture d’écran 2024-03-01 à 14 16 46" src="https://github.com/Zenika/feedzback/assets/1133214/b92cae35-7011-4402-90e3-c330a4c6d759">

**Comment by lisequesnel** [comment]
Pour ConfirmBeforeSubmit : Globalement c'est ok, peut-être que c'est utile de rajouter dans le texte que "la demande ne pourras plus être modifiée" et "le feedZback ne pourra plus être modifié"

**Comment by lisequesnel** [comment]
Pour LeaveForm : le wording est trop générique. On essaie ici de généraliser 2 actions différentes : "je tente de naviguer vers une autre page" et "je tente d'appliquer un brouillon qui va écraser le contenu du formulaire actuel". Je pense qu'il faut en faire 2 actions différentes pour éviter les termes trop génériques "action", "formulaire" et "confirmer".

 Et je viens de me dire que ça pourrait être plus user-friendly de lui proposer d'enregistrer le brouillon directement dans la pop-up si jamais il le souhaite dans le cas où la personne veut naviguer vers une autre page.

**Comment by avine** [comment]
> Pour LeaveForm : le wording est trop générique. On essaie ici de généraliser 2 actions différentes : "je tente de naviguer vers une autre page" et "je tente d'appliquer un brouillon qui va écraser le contenu du formulaire actuel". Je pense qu'il faut en faire 2 actions différentes pour éviter les termes trop génériques "action", "formulaire" et "confirmer".
> 
> Et je viens de me dire que ça pourrait être plus user-friendly de lui proposer d'enregistrer le brouillon directement dans la pop-up si jamais il le souhaite dans le cas où la personne veut naviguer vers une autre page.

- ça va être trop compliquer techniquement de différencier ces 2 cas (je navigue ou j'applique un brouillon).

**Comment by jeanphibaconnais** [comment]
Complexité de dév et de test 😁

**Comment by avine** [comment]
Voici les screenshots finaux pour les messages `ConfirmBeforeSubmit` :

- Lise n'a pas retenu le wording "Valider" ou "Continuer" pour terminer le formulaire
  - avec ce wording, on avait 1 clique pour "valider" le formulaire et un clique dans la popup pour "envoyer" concrètement le feedZback (ou la demande) 
- Donc on est bien resté sur le wording "Envoyer" pour terminer le formulaire
  - avec ce wording, on a donc 1 clique pour "envoyer" le formulaire et un second clique pour "confirmer" l'envoi (comme déjà évoqué, le use-case c'est le gars qui clique par mégarde sur le bouton "envoyer" dans le formulaire...) 

Les screenshots : 

### Demande de feedZback
<img width="1031" alt="Capture d’écran 2024-03-03 à 01 49 03" src="https://github.com/Zenika/feedzback/assets/1133214/9959480a-1a83-4d7b-9913-02eb522e971d">

### Donner du feedZback spontané (idem pour la page répondre à une demande de feedZback) 
<img width="1016" alt="Capture d’écran 2024-03-03 à 01 49 46" src="https://github.com/Zenika/feedzback/assets/1133214/c93ca5b4-3d3d-4bf3-b51f-a10674d57fb4">

### Page détails d'un feedZback demandé (en attente de réponse) 
- Le bouton archivé est toujours visible mais grisé si action pas disponible
<img width="991" alt="Capture d’écran 2024-03-03 à 01 51 07" src="https://github.com/Zenika/feedzback/assets/1133214/09bcb064-57c6-49e6-823d-f922ddfa0d8a">
- La popup pour confirmer l'archivage
<img width="997" alt="Capture d’écran 2024-03-03 à 01 51 51" src="https://github.com/Zenika/feedzback/assets/1133214/433ca89d-2021-4f2c-a63b-2c54c68e3d08">

**Comment by jeanphibaconnais** [comment]
Hello, deux choses rien à voir avec le wording  : 
- pourquoi ces ouvertures / réouvertures ? 😄 
- cela peut attendre le lundi pour pousser ces commentaires 😅

**Comment by avine** [comment]
> Hello, deux choses rien à voir avec le wording :
> 
> * pourquoi ces ouvertures / réouvertures ? 😄
> * cela peut attendre le lundi pour pousser ces commentaires 😅

Tu as raison, c'est juste que le projet touche à sa fin.
Je l'ai développé pendant mon interco et je commence ma nouvelle mission cette semaine.
Donc, j'ai poussé mes dernières modifs ce week-end...
A partir de maintenant, on rentre en phase TMA.
Je dois juste écrire la doc et faire des tests en fil rouge quand j'ai 5mn par-ci par-là...
Donc désolé pour les envois de messages pendant le we...

Et j'ai ré-ouvert la PR car je me suis aperçu après coup qu'il y a avait un loupé.

Il y a avait 2 options possibles : 
- Le formulaire "Valider" + la popup "Envoyer"
- Le formulaire "Envoyer" + la popup "Confirmer"

Or là, dans le rush, j'ai poussé dans le code : 
- Le formulaire "Envoyer" + la popup "Envoyer"

Et du coup, même à la démo, les gens ont souri car ça faisait genre, faut enovyer 2 fois...

Du coup, j'ai ré-ouvert la PR pour corriger ça et mettre : 
- Le formulaire "Envoyer" + la popup "Confirmer"
Puisque Lise a préféré "Envoyer" pour le formulaire.

**Comment by jeanphibaconnais** [comment]
> Donc désolé pour les envois de messages pendant le we...
Pas de soucis, je disais ça plus pour toi 😄 

>Je dois juste écrire la doc et faire des tests en fil rouge quand j'ai 5mn par-ci par-là...
arf pas le mieux de faire ça en // d'une nouvelle mission. bon courage en tout cas pour ta mission et essaye de prendre du temps (de ta mission) pour finir uniquement doc + tests, c'est le plus prioritaire que de nouvelles features

Ok et merci pour le fix. le bouton "envoyer" c'est très bien 👍

**Comment by lisequesnel** [comment]
all good pour la partie wording des demandes de feedzback, feedzbacks spontané et archivage de feedzback.

En revanche pour la partie LeaveForm, le wording est trop générique. On essaie de généraliser 2 actions différentes : "je tente de naviguer vers une autre page" et "je tente d'appliquer un brouillon qui va écraser le contenu du formulaire actuel". Idéalement, il faudrait 2 pop-up différentes. J'entends que c'est plus complexe, donc je propose un wording un peu plus contextuel pour les 2 cas : "Notez qu'en confirmant cette action, le FeedZback que vous avez commencé à rédigé sera perdu."

<img width="480" alt="image" src="https://github.com/Zenika/feedzback/assets/23451175/e694c676-e168-4e0a-860c-056fa968ab90">

**Comment by avine** [comment]
Ça marche. Je vais encore jeter un coup d'œil pour voir la complexité de m'avoir un texte entièrement custom pour ces popups aussi.

**Comment by avine** [comment]
Bon ben ça devrait être bon pour la contextualisation des popups `LeaveForm`.
Mais bon, ça a apporté son lot de complexité...

**Comment by avine** [comment]
C'est dispo en staging.

**Comment by avine** [comment]
Bien sûr que la code review c'est très bien et personne n'est à l'abri de faire des erreurs.
Cependant, sur FeedZback, je suis le seul développeur donc pratiquement ça va être compliqué.
De plus, y a des domaines sur lesquels je suis une bille complète, mais pour ce qui est d'Angular, je n'ai aucune problème pour dire que je sais ce que je fais.
J'ai un background de développeur front (je viens pas du Java...) et je fais du front avec Angular depuis 2017 sans interrumption.
Donc, sans avoir la grosse tête, je peux dire sans problème que je suis expert du framework (d'ailleurs je suis formateur Angular...).
Concrètement, les patterns que j'utilise dans Angular sont tellement éprouvés que je sais exactement où je vais.
Et le résultat est là : ceux qui ont jeté un coup d'oeil au code on pu dire qu'il est exemplaire (c'est-à-dire que ça serait bien que toutes les applications internes de Zenika aient ce niveau de qualité).
Et sur toute la durée du développement, je n'ai eu qu'un seul bug dans tout ce qui a été livré.

Parlons des tests maintenant.
Pour te donner du contexte, il faut savoir que bosser sur un projet interne en interco, c'est à mon sens plus dur que de bosser en mission chez un client.
Quand tu es chez un client, tu sais à priori que tu seras encore là le mois suivant, donc tu n'es pas pressé.
A l'inverse pour FeedZback, je ne savais jamais si 2 semaines plus tard, je serai encore dessus ou staffé en mission...
Donc ma position a été la suivante : 
- Développer au plus vite le MVP ("vite" ne veut pas dire faire des concessions - je n'en ai pas fait sur la qualité de code - ça veut plutôt dire que j'ai bossé 10h par jour - et c'est mon choix - personne ne m'a demandé ça - c'est juste que j'aime bien allé jusqu'au bout des choses)
- Une fois le MVP terminé (la fuite en avant), se poser et écrire une documentation exhaustive et des tests de non régressions pour permettre à d'autres développeurs de développer sereinement des nouvelles features sans avoir peur de tout casser.
- Là, justement, je commence une nouvelle mission la semaine prochaine (et cette semaine j'anime une formation Angular) et je suis très content d'avoir pu livrer 99% des features attendues !

En résumé, les prochaines étapes pour moi sont de produire en fil rouge (dès que j'ai 1h de libre par ci par là, je me mets sur FeedZback) : 
- Documentation (mon ambition c'est de produire une doc de qualité projet open source...) 
- Tests de non régression (là je n'ai pas encore de stratégie claire - tests E2E sur le chemin critique uniquement ou tests E2E et TU - sachant que l'écriture des TU prendrais un temps fou pour être exhaustifs... Donc sur les TU, va falloir que je trouve le bon curseur...).

**Comment by jeanphibaconnais** [comment]
Je ne remets pas du tout tes compétences tech en question. C'étaient des précos / recommandation de manière générale.

**Comment by avine** [comment]
J'avais bien compris. Je te donnais juste des insights sur le contexte du projet et mon positionnement face à ces questions absolument légitimes.
