### ISSUE TITLE
[Analytics] Afficher les feedbacks non répondus dans le looker studio

### ISSUE THREAD

**Issue by yasmineDoghri6** [Zenika/feedzback#475]
Sur le looker studio, on voudrait présenter l'évolution  des feedbacks non répondus (en attente) sur un graphe (un histogramme) par jour.

**Comment by yasmineDoghri6** [comment]
Les feedbacks non répondus sont les feedbacks sous la collection feedback ayant status=pending

**Comment by noancloarec** [comment]
@lisequesnel a reformulé le besoin hier en daily.  
L'objectif est de savoir s'il y a beaucoup de demandes de feedbacks qui restent sans réponse.  
On souhaite donc afficher la répartition de l'age des demandes.
Par exemple :
- 12 demandes ont moins de 5J
- 15 demandes ont entre 5 et 15j
- 20 demandes ont plus de 15j

**Comment by yasmineDoghri6** [comment]
Après une discussion avec @lisequesnel. Nous avons changé la répartition d'age des demandes sur plus d'intervalles car au bout d'un moment on va avoir qu'une seule classe avec l'ancienne répartition "plus de 15j" .
La nouvelle répartition est la suivante :
- entre 6 mois et ∞
- entre [3 et 6 mois[
- entre [1 et 3 mois[
- entre [2 semaines et 1 mois[
- entre [0 et 2 semaines[

**Comment by noancloarec** [comment]
Résolu dans #521
