### ISSUE TITLE
Ajouter un champ de contexte de feedback

### ISSUE THREAD

**Issue by yannbertrand** [Zenika/feedzback#701]
# Need from the user's point of view

Lors l'envoie de feedback on retrouve les champs suivants :
- Mail de la personne à qui on fait le feedback
- Points positifs
- Axes d'améliorations
- Commentaire

Je trouverai intéressant d'avoir un champ qui précise pour quel contexte on donne ce feedback : préciser les rôles, l'équipe, le type de mission... Par défaut je vais mettre ça dans "commentaire" mais je trouve qu'il manque de précision.

**Comment by avine** [comment]
Issue closed because of duplicate: #585
